# Generated by Django 5.2.1 on 2025-06-16 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('additional', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('cart', 'Тележка'), ('bunker', 'Бункер'), ('system', 'Система')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('additional', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wifi_ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('wifi_password', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('error', 'Ошибка'), ('warning', 'Предупреждение'), ('ok', 'OK')], default='ok', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('additional', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('jwt', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_period', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.feed')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fish_app.period')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.pool')),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('done', 'Выполнено'), ('planned', 'Запланировано'), ('in-progress', 'В процессе'), ('error', 'Ошибка')], default='planned', max_length=15)),
                ('result', models.JSONField(blank=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.feed')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.pool')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.timetable')),
            ],
        ),
    ]
